/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2018-11-24 10:00:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class studentProfile2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the header */\r\n");
      out.write("header {\r\n");
      out.write("    background-color: #666;\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-size: 35px;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Create two columns/boxes that floats next to each other */\r\n");
      out.write("aside{\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 30%;\r\n");
      out.write("    height: 300px; /* only for demonstration, should be removed */\r\n");
      out.write("    background: #ccc;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the list inside the menu */\r\n");
      out.write("nav ul {\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("article {\r\n");
      out.write("    float: left;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    width: 70%;\r\n");
      out.write("    background-color: #ccc;\r\n");
      out.write("    height: 300px; /* only for demonstration, should be removed */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Clear floats after the columns */\r\n");
      out.write("section:after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    display: table;\r\n");
      out.write("    clear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the footer */\r\n");
      out.write("footer {\r\n");
      out.write("    background-color: #ccc;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive layout - makes the two columns/boxes stack on top of each other instead of next to each other, on small screens */\r\n");
      out.write("/*@media (max-width: 600px) {\r\n");
      out.write("    nav, article {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: auto;\r\n");
      out.write("    }\r\n");
      out.write("}*/\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("    width:100%;\r\n");
      out.write("}\r\n");
      out.write("table, th, td {\r\n");
      out.write("    border: 1px solid black;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    padding:3px;\r\n");
      out.write("}\r\n");
      out.write("th, td {\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("    text-align:left;\r\n");
      out.write("}\r\n");
      out.write("table#t01 tr:nth-child(even) {\r\n");
      out.write("    background-color: #eee;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("table#t01 tr:nth-child(odd) {\r\n");
      out.write("   background-color: #fff;\r\n");
      out.write("       \r\n");
      out.write("}\r\n");
      out.write("table{\r\n");
      out.write("border-spacing:3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 8px 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("    background-color: #ddd;\r\n");
      out.write("    color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".previous {\r\n");
      out.write("    background-color: #f1f1f1;\r\n");
      out.write("    color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".next {\r\n");
      out.write("    background-color: #4CAF50;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".round {\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("  <h2>Student Profile</h2>\r\n");
      out.write("  \r\n");
      out.write("  <div align=\"right\">\r\n");
      out.write("\r\n");
      out.write("<img src=\"F:\\library mangement\\th.jpg\" alt=\"HTML tutorial\" style=\"float:left;width:42px;height:42px;border:0;\"> \r\n");
      out.write("\r\n");
      out.write("<a href=\"#\" class=\"previous round\">&#8249;</a>\r\n");
      out.write("</div>\r\n");
      out.write("  <div><hr></div>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write(" <div class=\"btn-group\" align=\"left\">\r\n");
      out.write(" <align=\"left\">   <button type=\"button\" class=\"btn btn-primary\" >Apple</button>\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary\">Samsung</button>\r\n");
      out.write("  \r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("    Sony<span class=\"caret\"></span></button>\r\n");
      out.write("  </align>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("<aside>\r\n");
      out.write("<img src=\"F:\\library mangement\\man.jpg\" alt=\"Smiley face\" width=\"100%\" height=\"100%\" align=\"left\"></div>\r\n");
      out.write("\r\n");
      out.write("</aside>\r\n");
      out.write("  <nav>\r\n");
      out.write("    <ul>\r\n");
      out.write("      <li>Jaime Marine</li>\r\n");
      out.write("      <li>Course: STANDARD 7</li>\r\n");
      out.write("      <li>Batch:2010</li>\r\n");
      out.write("       <li>Adm no:201</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </nav>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</section>\r\n");
      out.write("<center>\r\n");
      out.write("<footer>\r\n");
      out.write("<font color=\"blue\" border-spacing:\"3px\">\r\n");
      out.write(" <table id=\"t01\" >\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=40%>Firstname</td>\r\n");
      out.write("    <td width=60%>Lastname</td> \r\n");
      out.write("    \r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=40%>Jill</td>\r\n");
      out.write("    <td width=60%>Smith</td>\r\n");
      out.write("   \r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=40%>Eve</td>\r\n");
      out.write("    <td width=60%>Jackson</td>\r\n");
      out.write("    \r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=40%>John</td>\r\n");
      out.write("    <td width=60%>Doe</td>\r\n");
      out.write("   \r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</font>\r\n");
      out.write("</footer></center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
